### ISSUE TITLE
Unable to get indexm snippet to work in a html file.

### ISSUE THREAD

**Issue by js1972** [qmacro/ui5-snippets#6]
Hi, Just wondering if you have the ui5indexm snippet working on your end. It does nothing for me but the ui5starter and ui5indexmspmvc snippets work fine.

I noticed there was allot of mixed spaces and tabs so cleaned that up, but ui5indexm still doesn't work for me.

**Comment by js1972** [comment]
Cleaned up the mixed whitespace to be tabs only and re-arranged the order of the snippets and its magically working now...

**Comment by qmacro** [comment]
cheers - may be related to this: http://pipetree.com/qmacro/blog/2015/01/atom-snippets-tabs-and-cson-parsing/ - will be tidying stuff up soon (tuits required!)

**Comment by js1972** [comment]
I see you've only changed the tab handling in your fosdem-2105 branch...
